import { Article, Prayer, Campaign } from "@/types";

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "Nowe centrum pomocy dla uchodźców",
    excerpt: "Dzięki Waszemu wsparciu otworzyliśmy nowe centrum, które miesięcznie pomaga ponad 500 rodzinom.",
    content: `Dzięki nieocenionej pomocy naszych darczyńców z wielką radością ogłaszamy otwarcie nowego centrum pomocy dla uchodźców w centrum Warszawy.\n\nCentrum oferuje:\n- Pomoc prawną i doradztwo\n- Kursy języka polskiego\n- Pomoc psychologiczna\n- Wsparcie w znalezieniu pracy\n\nCo miesiąc pomagamy ponad 500 rodzinom znaleźć swoje miejsce w Polsce. To wszystko dzięki Wam.\n\nJeśli chcesz wesprzeć nasze działania, możesz złożyć darowiznę bezpośrednio przez aplikację.`,
    image_url: "/images/article1.jpg",
    category: "Aktualności",
    published_at: "2024-12-15T10:00:00Z",
    author: "Anna Kowalska",
  },
  {
    id: "2",
    title: "Wigilia dla samotnych — relacja",
    excerpt: "W tym roku przy wspólnym stole zasiadło 300 osób, które spędziłyby święta samotnie.",
    content: `To był wyjątkowy wieczór. Przy nakrytym do wigilii stole zasiadło 300 osób, które bez naszej inicjatywy spędziłyby Boże Narodzenie samotnie.\n\nWśród gości byli seniorzy z domów pomocy społecznej, bezdomni, uchodźcy oraz wolontariusze. Wspólnie dzieliliśmy się opłatkiem i śpiewaliśmy kolędy.\n\nDziękujemy wszystkim darczyńcom, wolontariuszom i sponsorom, którzy uczynili to możliwym.`,
    image_url: "/images/article2.jpg",
    category: "Relacje",
    published_at: "2024-12-28T09:00:00Z",
    author: "Ks. Marek Wiśniewski",
  },
  {
    id: "3",
    title: "Petycja o ochronę rodziny — dołącz!",
    excerpt: "Zbieramy podpisy pod petycją do parlamentu. Potrzebujemy 10 000 głosów do końca miesiąca.",
    content: `Zwracamy się do Was z apelem o podpisanie petycji skierowanej do Sejmu RP w sprawie wzmocnienia ochrony rodziny w polskim prawie.\n\nPetycja dotyczy:\n1. Rozszerzenia wsparcia dla rodzin wielodzietnych\n2. Ochrony praw rodziców w systemie edukacji\n3. Zwiększenia nakładów na opiekę nad seniorami\n\nAby petycja została rozpatrzona, potrzebujemy 10 000 podpisów do końca stycznia. Mamy już 6 742. Pomóż nam dotrzeć do celu!\n\nPodpisz poniżej i udostępnij znajomym.`,
    image_url: "/images/article3.jpg",
    category: "Akcje",
    published_at: "2025-01-05T08:00:00Z",
    author: "Redakcja",
  },
  {
    id: "4",
    title: "Raport roczny 2024 — transparentność naszych działań",
    excerpt: "Jak wydaliśmy każdą złotówkę Waszego wsparcia. Pełny raport finansowy i merytoryczny.",
    content: `Z dumą i wdzięcznością przedstawiamy raport z działalności Fundacji za rok 2024.\n\n**Podsumowanie finansowe:**\n- Łączne przychody: 2 340 000 zł\n- 89% środków trafiło bezpośrednio do beneficjentów\n- Koszty administracyjne: 11%\n\n**Działania merytoryczne:**\n- 1 247 rodzin objętych stałą pomocą\n- 34 akcje społeczne\n- 12 projektów edukacyjnych\n- 8 000 wolontariuszy\n\nDziękujemy każdemu darczyńcy z osobna. Wasze zaufanie jest dla nas najcenniejszym darem.`,
    image_url: "/images/article4.jpg",
    category: "Raporty",
    published_at: "2025-01-10T12:00:00Z",
    author: "Zarząd Fundacji",
  },
];

export const mockPrayers: Prayer[] = [
  {
    id: "1",
    title: "Ojcze Nasz",
    content: "Ojcze nasz, któryś jest w niebie,\nniech się święci imię Twoje;\nniech przyjdzie królestwo Twoje;\nniech Twoja wola się spełnia na ziemi, tak jak w niebie.\nChleba naszego powszedniego\ndaj nam dzisiaj;\ni przebacz nam nasze winy,\njako i my przebaczamy tym, którzy przeciw nam zawinili;\ni nie wódź nas na pokuszenie,\nale nas zbaw ode złego. Amen.",
    category: "Podstawowe",
    language: "pl",
    tags: ["codzienna", "modlitwa Pańska"],
  },
  {
    id: "2",
    title: "Zdrowaś Maryjo",
    content: "Zdrowaś Maryjo, łaski pełna,\nPan z Tobą,\nbłogosławionaś Ty między niewiastami\ni błogosławiony owoc żywota Twojego, Jezus.\nŚwięta Maryjo, Matko Boża,\nmódl się za nami grzesznymi\nteraz i w godzinę śmierci naszej. Amen.",
    category: "Maryjna",
    language: "pl",
    tags: ["maryjna", "różaniec"],
  },
  {
    id: "3",
    title: "Różaniec — Tajemnice Radosne",
    content: "I. Zwiastowanie Najświętszej Maryi Pannie\nII. Nawiedzenie Świętej Elżbiety\nIII. Narodzenie Pana Jezusa\nIV. Ofiarowanie Pana Jezusa w świątyni\nV. Znalezienie Pana Jezusa w świątyni\n\nNa każdą tajemnicę:\n- 1× Ojcze Nasz\n- 10× Zdrowaś Maryjo\n- 1× Chwała Ojcu",
    category: "Różaniec",
    language: "pl",
    tags: ["różaniec", "maryjna", "poniedziałek", "sobota"],
  },
  {
    id: "4",
    title: "Modlitwa za darczyńców",
    content: "Panie Boże, w Trójcy Świętej jedyny,\ndziękujemy Ci za dobroć serc tych,\nktórzy wspierają nasze dzieło.\nNiech Twoje błogosławieństwo spłynie na nich\nna każdy dzień ich życia,\nniech Twoja łaska mnoży owoce ich ofiarności\ni napełnia ich serca pokojem i radością.\nPrzez Chrystusa Pana naszego. Amen.",
    category: "Specjalne",
    language: "pl",
    tags: ["wdzięczność", "darczyńcy", "błogosławieństwo"],
  },
  {
    id: "5",
    title: "Koronka do Bożego Miłosierdzia",
    content: "Na początku:\nOjcze Nasz, Zdrowaś Maryjo, Wierzę w Boga.\n\nNa paciorka Ojcze Nasz:\n\"Ojcze Przedwieczny, ofiaruję Ci Ciało i Krew,\nDuszę i Bóstwo najmilszego Syna Twojego,\na Pana naszego Jezusa Chrystusa,\nna przebłaganie za grzechy nasze\ni całego świata.\"\n\nNa paciorkach Zdrowaś Maryjo (10 razy):\n\"Dla Jego bolesnej Męki\nmiej miłosierdzie dla nas i całego świata.\"\n\nNa zakończenie (3 razy):\n\"Święty Boże, Święty Mocny,\nŚwięty Nieśmiertelny,\nzmiłuj się nad nami i nad całym światem.\"",
    category: "Koronki",
    language: "pl",
    tags: ["miłosierdzie", "godzina trzecia", "koronka"],
  },
  {
    id: "6",
    title: "Pater Noster",
    content: "Pater noster, qui es in cælis:\nsanctificétur nomen tuum;\nadvéniat regnum tuum;\nfiat volúntas tua,\nsicut in cælo, et in terra.\nPanem nostrum cotidiánum da nobis hódie;\net dimítte nobis débita nostra,\nsicut et nos dimíttimus debitóribus nostris;\net ne nos indúcas in tentatiónem;\nsed líbera nos a malo. Amen.",
    category: "Łacińskie",
    language: "la",
    tags: ["łacina", "tradycja"],
  },
  {
    id: "7",
    title: "Modlitwa poranna",
    content: "Boże, dziękuję Ci za noc spokojną\ni za nowy dzień, który mi dajesz.\nOfiaruję Ci wszystkie moje myśli, słowa i uczynki\ntego dnia.\nNiech wszystko, co czynię,\nbędzie na Twoją chwałę i ku pożytkowi bliźnich.\nStrzeż mnie od grzechu\ni prowadź drogą Twoich przykazań.\nAmen.",
    category: "Poranna/Wieczorna",
    language: "pl",
    tags: ["poranna", "codzienna"],
  },
  {
    id: "8",
    title: "Modlitwa wieczorna",
    content: "Boże w Trójcy Świętej Jedyny,\ndziękuję Ci za dzień dzisiejszy,\nza wszystko dobro, jakie przez ten dzień otrzymałem.\nPrzebacz mi wszystkie grzechy i zaniedbania.\nPołącz mój nocny spoczynek\nz odpoczynkiem Jezusa w grobie\ni z Jego chwalebnym Zmartwychwstaniem.\nAmen.",
    category: "Poranna/Wieczorna",
    language: "pl",
    tags: ["wieczorna", "codzienna"],
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    title: "Pomoc dla rodzin z Ukrainy",
    description: "Zapewniamy schronienie, jedzenie i edukację dla rodzin, które uciekły przed wojną.",
    goal_amount: 100000,
    current_amount: 67340,
    currency: "PLN",
    ends_at: "2025-03-31T23:59:59Z",
    active: true,
  },
  {
    id: "2",
    title: "Szkoła dla dzieci z ubogich rodzin",
    description: "Fundujemy stypendia i wyprawki szkolne dla 200 dzieci z najuboższych rodzin.",
    goal_amount: 50000,
    current_amount: 42800,
    currency: "PLN",
    active: true,
  },
  {
    id: "3",
    title: "Dom Modlitwy — remont dachu",
    description: "Nasz Dom Modlitwy wymaga pilnego remontu dachu. Każda złotówka się liczy.",
    goal_amount: 30000,
    current_amount: 8900,
    currency: "PLN",
    ends_at: "2025-04-30T23:59:59Z",
    active: true,
  },
];
